version: "3.9"
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    networks: 
      - cloud
    depends_on:
      - nextclouddb
    ports:
      - 80:80
    volumes:
    - ./data:/var/www/html/data
    - ./config:/var/www/html/config
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb

  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    networks: 
      - cloud
    volumes:
      - ./nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
networks:
  cloud:
    name: cloud
    driver: bridge
